SELECT * FROM [INFORMATION_SCHEMA].[COLUMNS] C
WHERE 
		C.[TABLE_NAME] NOT LIKE 'Entity.%'
	AND	C.[DATA_TYPE] = 'decimal'
ORDER BY 
	C.[TABLE_SCHEMA],
	C.[TABLE_NAME];

SELECT 
	 C.[DATA_TYPE]
	,COUNT(*)
FROM [INFORMATION_SCHEMA].[COLUMNS] C
WHERE C.[TABLE_NAME] NOT LIKE 'Entity.%'
GROUP BY C.[DATA_TYPE];
