EXEC sp_configure filestream_access_level, 2;
GO
RECONFIGURE;
GO

ALTER DATABASE [Nimble]
ADD FILEGROUP [FILESTREAM] CONTAINS FILESTREAM;
GO

ALTER DATABASE [Nimble]
ADD FILE
(
	NAME		= 'FILESTREAM',
	FILENAME	= 'C:\Programs\Database\MSSQL\2012\Nimble'
)
TO FILEGROUP [FILESTREAM];
GO
